#!/usr/bin/env bash
# transfers a file from our client to a server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

FILE="$1"
IP="$2"
USER="$3"
SSHKEY="$4"

if [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$FILE" "${USER}@${IP}":~/
else
    scp -o StrictHostKeyChecking=no -i "$SSHKEY" "$FILE" "${USER}@${IP}":~/

fi