#!/usr/bin/env bash
# Nginx server so that /redirect_me

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "19a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
