#!/usr/bin/env bash
# Nginx server so that /redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
locationv='\404.html {\nroot /usr/share/nginx/html;\ninternal;\n}'
sed -i "19a error_page 404 /404.html; location = $locationv" /etc/nginx/sites-available/default
service nginx restart
