#!/usr/bin/env bash
# Install your load balancer

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo "
frontend front
        bind *:80
	    default_backend web-back
backend web-back
        balance roundrobin
        server 2394-web-01 35.237.105.160:80 check
        server 2394-web-02 54.221.65.216:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
