#!/usr/bin/env bash
#Superstitious numbers 
burger=1
while [ $burger -lt 21 ];
do
    echo $burger
    case $burger in
    4)
        echo "bad luck from China"
    ;;
    9)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from Italy"
    ;;
    esac
  	((burger++))
done
